apiVersion: v1
entries:
  mychart:
  - apiVersion: v2
    appVersion: "1.0"
    created: "2025-10-06T09:45:24.713351805Z"
    description: A Helm chart for deploying a Node.js app
    digest: fc179724ae8b0f2f5bbebbc898f865b65ff165eaead484e68e755b8724b3ecc4
    name: mychart
    type: application
    urls:
    - https://kanupriya1801.github.io/my-helm-charts/charts/mychart-0.1.0.tgz
    version: 0.1.0
generated: "2025-10-06T09:45:24.713062456Z"
